config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  devise_scope  :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources :users do 
    resources :groups do
      resources :expenditures
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#splash"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expenditure.rb
class Expenditure < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :name, presence: true
  validates :amount, presence: true

  def total_expenditures(id)
    total = 0
    Expenditure.where(group_id: id).each do |expenditure|
      total += expenditure.amount
    end
    total
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :expenditures

  validates :name, presence: true

  def user_name(user_id)
    User.find(user_id).full_name
  end

  def total_spent(id)
    expenditures = Expenditure.where(group_id: id)
    total = 0
    expenditures.each do |expenditure|
      total += expenditure.amount
    end
    total
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, dependent: :destroy
  has_many :expenditures, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(_resource)
    user_groups_path(current_user)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[full_name])
  end
end

app/controllers/expenditures_controller.rb
class ExpendituresController < ApplicationController
  before_action :authenticate_user!
  before_action :set_expenditure, only: %i[show edit update destroy]

  # GET /expenditures or /expenditures.json
  def index
    @group_id = Group.find(params[:group_id])
    @expenditures = Expenditure.where(group_id: @group_id.id)
  end

  # GET /expenditures/new
  def new
    @group_id = Group.find(params[:group_id]).id
    @expenditure = Expenditure.new
  end

  # POST /expenditures or /expenditures.json
  def create
    @expenditure = Expenditure.new(expenditure_params)
    @expenditure.user_id = current_user.id
    @group = Group.find(params[:group_id])

    @expenditure.group_id = @group.id

    if @expenditure.save
      redirect_to user_group_expenditures_url(user_id: current_user.id, group_id: @group.id)
    else
      render :new
    end
  end

  # PATCH/PUT /expenditures/1 or /expenditures/1.json
  def update
    respond_to do |format|
      if @expenditure.update(expenditure_params)
        format.html { redirect_to expenditure_url(@expenditure), notice: 'Expenditure was successfully updated.' }
        format.json { render :show, status: :ok, location: @expenditure }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expenditure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenditures/1 or /expenditures/1.json
  def destroy
    @expenditure.destroy

    respond_to do |format|
      format.html { redirect_to expenditures_url, notice: 'Expenditure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_expenditure
    @expenditure = Expenditure.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def expenditure_params
    params.require(:expenditure).permit(:name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  def index
    @groups = Group.where(user_id: current_user.id)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    if @group.save
      flash[:success] = 'group created succesfully'
      redirect_to user_groups_path(current_user)
    else
      render 'new'
    end
  end

  def show; end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenditures_helper.rb
module ExpendituresHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/expenditures/_expenditure.html.erb
<div id="<%= dom_id expenditure %>">

<div class= 'category-container'>
  <div><strong><%= @group_id.name %>:</strong> </div>
    <div> <%= expenditure.name %> </div>
    <div>$ <%= expenditure.amount %></div>
  </div>
</div>

app/views/expenditures/_form.html.erb
<%= form_with(model: expenditure) do |form| %>
  <% if expenditure.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expenditure.errors.count, "error") %> prohibited this expenditure from being saved:</h2>

      <ul>
        <% expenditure.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :group_id, style: "display: block" %>
    <%= form.text_field :group_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/expenditures/index.html.erb
<div class="nav-header ">
  <div>
      <%= link_to  user_groups_path do %>
        <%= image_tag "back.svg", style: 'height:10px; width:auto;' %>
      <% end  %>
  </div>
  <h4 class="text-gray-4 ">Expenditures</h4> 
  <div> </div>
</div>

<div class= "expenditures-total">
  <div class="icon-container"> 
    <%= image_tag "#{@group_id.icon}.png", style: 'height:40px; width:auto;' %> 
  </div>
  <% if @expenditures.count > 0 %>
    <div class=" flex-column">
      <p> <strong>Category:</strong> <%= @group_id.name %> </p>
      <p> <strong>Total spent:</strong> $<%= @expenditures.first.total_expenditures(@group_id) %></p>
    </div>
  <%end %>
</div>

<div id="expenditures">
  <% @expenditures.each do |expenditure| %>
    <%= render expenditure %>
    <p>
     
    </p>
  <% end %>
</div>
<div class='add-ne-category-btn-container-main'>
  <div class= 'add-ne-category-btn-container'>
    <%= link_to "Add a new expenditure", new_user_group_expenditure_path(user_id: current_user.id, group_id: @group_id), class: 'add-ne-category-btn text-gray-4' %>
  </div> 
</div> 

app/views/expenditures/new.html.erb
<%= form_with(model: @expenditure,  url:"/users/#{current_user.id}/groups/#{@group_id}/expenditures" ) do |form| %>

  <div class="nav-header">
    <div>
      <%= link_to  user_group_expenditures_url(user_id: current_user.id, group_id: @group_id) do %>
        <%= image_tag "back.svg", style: 'height:10px; width:auto;' %>
      <% end  %>
    </div>
    <h4 class="text-gray-4">NEW EXPENDITURE </h4>
    <div class="actions">
      <%=  form.submit 'NEXT', class:" bg-light nav-right-action text-gray-4" %>
    </div>
  </div>


  <% if @expenditure.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@expenditure.errors.count, "error") %> prohibited this expenditure from being saved:</h2>

      <ul>
        <% @expenditure.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class= "form-group-custom" >
      <%= form.text_field :name,   class:"form-control-custom", placeholder: "Enter expenditure name", autofocus: true %>
  </div>

  <div class= "form-group-custom" >
      <%= form.number_field :amount,   class:"form-control-custom", placeholder: "Enter expenditure amount", autofocus: true %>
  </div>

  <div class= "form-group d-flex" >
  
  <div class='add-ne-category-btn-container-main'>
    <div class= 'add-ne-category-btn-container'>
        <%=  form.submit ('SUBMIT'), class:" add-ne-category-btn text-gray-4" %>
      </div> 
    </div> 
  </div> 
<% end %>

app/views/groups/index.html.erb
<div class="nav-header ">
  <h4 class="text-gray-4 ">CATEGORIES</h4>
  <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:  'nav-link text-gray-4' %>
</div>

<div id="categories">
  <% if @groups %>
    <% @groups.each do |group| %>
      <a href = "/users/<%= group.user_id %>/groups/<%= group.id %>/expenditures" >
        <div class= 'category-container'>
          <div class="icon-container"> 
            <%= image_tag "#{group.icon}.png", style: 'height:40px; width:auto;' %>  <%= group.name%>
          </div>
          <div><%= group.user_name(group.user_id) %> </div>

          <div> Total: $<%= group.total_spent(group.id)%></div>
        </div>
      </a>
    <% end %>
  <% end %>
</div>
<div class='add-ne-category-btn-container-main'>
  <div class= 'add-ne-category-btn-container'>
    <%= link_to 'ADD A NEW CATEGORY', new_user_group_path(current_user), class:  'add-ne-category-btn text-gray-4' %>
  </div>
</div>

app/views/groups/new.html.erb
<%= form_with(model: @group, url: user_groups_path) do |f| %>

  <div class="nav-header">
    <div>
      <%= link_to  :back do %>
        <%= image_tag "back.svg", style: 'height:10px; width:auto;' %>
      <% end  %>
    </div>
    <h4 class="text-gray-4"> NEW CATTEGORY</h4>
    <div class="actions">
      <%=  f.submit ('NEXT'), class:" bg-light nav-right-action text-gray-4" %>
    </div>
  </div>

    <div class= "form-group-custom" >
      <%= f.text_field :name,   class:"form-control-custom", placeholder: "Enter category name", autofocus: true %>
    </div>

    <div class= "form-group-custom" >
      <%= f.label :icon, "Select label for an icon:", class: "label text-gray-2" %>
      <%= f.select  :icon, ["Education", "Entertainment", "Healthcare", "Shopping", "Utilities", "Other" ], class:"form-control-custom" %>
    </div>
    
  <div class='add-ne-category-btn-container-main'>
    <div class= 'add-ne-category-btn-container'>
        <%=  f.submit ('SUBMIT'), class:" add-ne-category-btn text-gray-4" %>
      </div> 
    </div> 
  </div> 
  
  <% end %>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>

<div>
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Destroy this group", @group, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Budget App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container w-100 h-100">
      <br/>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/splash.html.erb
<div class = "col-xs-12 d-flex flex-column height-full">
  <div class = "d-flex justify-content-center align-items-center height-80">
   <h1 class="text-gray-2">Budget App<h1>
  </div>
  <div class = " d-flex flex-column p-0 height-20">
    <%= link_to "Log in", new_user_session_path, class:'btn-action bg-blue text-gray-4' %>
    <%= link_to "Sign up", new_user_registration_path, class:'btn-action text-gray-2' %>
  </div>
</div>